const SpectrumCards: [string, string][] = [
  ["Mavais acteur", "Bon acteur"],
  ["Basique", "Hipster"],
  ["Sans-valeur", "Inestimable"],
  ["Inné", "Appris"],
  ["Se passe lentement", "Se passe rapidement"],
  ["Travail", "Carrière"],
  ["Rond", "Pointu"],
  ["Prouve que Dieu existe", "Prouve que Dieu n'existe pas"],
  ["Aimé", "Haï"],
  ["Le côté lumineux de la Force", "Le côté obscure de la force Force"],
  ["Stupide", "Génial"],
  ["Artisanal", "Industriel"],
  ["Personne ne le fait", "Tout le monde le fait"],
  ["Ephémère", "Durable"],
  ["Tâche dangeureuse", "Tâche inoffensive"],
  ["Fantaisie", "Science-Fiction"],
  ["Standard", "Fantaisiste"],
  ["A mauvaise reputation", "A bonne reputation"],
  ["Ethique à manger", "Immoral à manger"],
  ["Blockbuster", "Palme d'Or"],
  ["Démodé", "A la mode"],
  ["Défenseur des libertés", "Terroriste"],
  ["Mauvais superpouvoir", "Bon superpouvoir"],
  ["Inutile", "Efficace"],
  ["Meilleur chaud", "Meilleur froid"],
  ["Carré", "Rond"],
  ["Temporaire", "Permanent"],
  ["Ressemble à une personne", "Ne ressemble pas à une personne"],
  ["Nul", "Cool"],
  ["Personne vivante la plus nulle", "Personne vivante la plus cool"],
  ["Sous-évalué", "Sur-évalué"],
  ["Nourriture sale", "Nourriture propre"],
  ["Impardonnable", "Pardonnable"],
  ["Echec", "chef-d'oeuvre"],
  ["Inoffensif", "Nuisible"],
  ["Gryffondor", "Serpentard"],
  ["Sale", "Hygienique"],
  ["Mauvaise musique", "Bonne musique"],
  ["Inutile", "Utile"],
  ["Un film que Godzilla rendrait moins bien", "Un film que Godzilla rendrait meilleur"],
  ["sans importance", "Important"],
  ["Facile à épeler", "Difficile à épeler"],
  ["Vice", "Vertu"],
  ["Musicien trop peu connu", "Musicien surfait"],
  ["Activité prisée", "Activité impopulaire"],
  ["Divisé", "Complet"],
  ["Incertain", "Fiable"],
  ["Facile à tuer", "Difficile à tuer"],
  ["Instable", "Stable"],
  ["Animal doux", "Animal dur"],
  ["Mauvais programme TV", "Bon programme TV"],
  ["Traditionellement masculin", "Traditionallement féminin"],
  ["Partie du corps inutile", "Partie du corps utile"],
  ["A la mode", "Classique"],
  ["Faible", "Fort"],
  ["Céréales dégoûtantes", "Céréales délicieuses"],
  ["Mauvais", "Bien"],
  ["Peu addictif", "Très addictif"],
  ["Inutile en cas d'urgence", "Utile en cas d'Urgence"],
  ["Pour les enfants", "Pour les adultes"],
  ["Méchant", "Héro"],
  ["Activité qui mériterait à être connue", "Activité sur-vendue"],
  ["Ennuyeux", "Excitant"],
  ["Sent bon", "Pue"],
  ["Impopulaire", "Populaire"],
  ["Ami", "Ennemi"],
  ["Invention Inutile", "Invention utile"],
  ["De gauche", "De droite"],
  ["Chaud", "Froid"],
  ["Normal", "Bizarre"],
  ["Fade", "Coloré"],
  ["Sans calories", "Plein de calories"],
  ["Matière facile", "Matière difficile"],
  ["Inconnu", "Célèbre"],
  ["Rare", "Commun"],
  ["Emoji banal", "Emoji sexy"],
  ["Bon marché", "Cher"],
  ["Arme sous-estimée", "Arme sur-estimée"],
  ["Fait se sentir bien", "Fait se sentir mal"],
  ["Accessoire", "Essentiel"],
  ["Sale", "Propre"],
  ["Requiert de la chance", "Requiert du talent"],
  ["Préjudiciable", "Avantageux"],
  ["Sujet ennuyeux", "Sujet passionnant"],
  ["Relax", "Formel"],
  ["Sous-payé", "Sur-payé"],
  ["Sec", "Mouillé"],
  ["Talent sous-estimé", "Talent sur-estimé"],
  ["Interdit", "Encouragé"],
  ["Chanson triste", "Chanson heureuse"],
  ["Fragile", "Durable"],
  ["Génie", "Idiot"],
  ["Bien", "Mal"],
  ["Pire de l'année", "Meilleur de l'année"],
  ["Mauvaise habitude", "Bonne habitude"],
  ["Chat", "Chien"],
  ["Sage", "Intelligent"],
  ["Difficile à faire", "Facile à faire"],
  ["Activité mentale", "Activité physique"],
  ["Sujet concensuel", "Sujet controversé"],
  ["Plaisir interdit", "Relation ouverte"],
  ["Sans talent", "Doué"],
  ["Difficile à trouver", "Facile à trouver"],
  ["Homme moche", "Bel homme"],
  ["Difficile à retenir", "Facile à retenir"],
  ["Inculte", "Eduqué"],
  ["Malsain", "Sain"],
  ["Mauvaise personne", "Bonne personne"],
  ["Historiquement important", "Historiquement anecdotique"],
  ["Sans poils", "Poilu"],
  ["Inflexible", "Flexible"],
  ["Animal de compagnie normal", "Animal de compagnie exotique"],
  ["Introverti", "Extraverti"],
  ["Le livre était meilleur", "Le film était meilleur"],
  ["Mauvais film", "Bon film"],
  ["Moche", "Magnifique"],
  ["Personne mature", "Personne immature"],
  ["Objet qui mérite à être connu", "Objet sur-vendu"],
  ["Ordinaire", "Extraordinaire"],
  ["Difficile à prononcer", "Facile à prononcer"],
  ["Fait n'importe comment", "Bien fait"],
  ["Pas un sandwich", "Un sandwich"],
  ["Dangereux", "Sûr"],
  ["Culturellement important", "Culturellement insignifiant"],
  ["Optionnel", "Obligatoire"],
  ["Lettre de l'alphabet sous-utilisée", "Letter de l'alphabet sur-utilisée"],
  ["Mauvaise qualité", "Haute qualité"],
  ["Animal pas sexy", "Animal sexy"],
  ["Lieu calme", "Lieu agité"],
  ["Comedie", "Drame"],
  ["Nécessité", "Souhait"],
  ["Nourriture sèche", "Nourriture humide"],
  ["Remplaçable", "Irremplaçable"],
  ["Pire athlète de tous les temps", "Meilleure athlète de tous les temps"],
  ["Immoral", "Ethique"],
  ["Hobby ennuyeux", "Hobby intéressant"],
  ["Mauvais sur une pizza", "Bon sur une pizza"],
  ["Dystopie", "Utopie"],
  ["Rugueux", "Lisse"],
  ["Mauvais pour toi", "Bon pour toi"],
  ["Paisible", "Chaotique"],
  ["Film inconnu", "Film populaire"],
  ["A mauvais goût", "A bon goût"],
  ["Compétition", "Jeu"],
  ["Film triste", "Film joyeux"],
  ["Perte de temps", "Bon usage de son temps"],
  ["Entreprise respectable", "Entreprise aux pratiques pas nettes"],
  ["Snack", "Repas"],
  ["Incroyable", "Plausible"],
  ["Vulgaire", "Classe"],
  ["Sens mauvais", "Sens bon"],
  ["Star Wars", "Star Trek"],
  ["Animal qui fait peur", "Animal chou"],
  ["Grand public", "Niche"],
  ["Noir", "Blanc"],
  ["Acteur peu connu", "Acteur très connu"],
  ["Difficile à utiliser", "Facile à utiliser"],
  ["Fatigué", "Plein d'énergie"],
  ["Années 80", "Années 90"],
  ["Mauvaise personne", "Bonne personne"],
  ["Subsistance", "Haute cuisine"],
  ["Mou", "Dur"],
  ["Chose normale à posséder", "Chose étrange à posséder"],
  ["Droit", "Courbé"],
  ["Modèle", "Mauvaise influence"],
  ["Sujet d'étude inutile", "Sujet d'étude utile"],
  ["Personne méchante", "Personne gentille"],
  ["Film d'action", "Film d'adventure"],
];

const AdvancedSpectrumCards: [string, string][] = [
  ["Court", "Long"],
  ["Pire année dans l'histoire", "Meilleure année dans l'histoire"],
  ["Connu", "Inconnu"],
  ["Dieu le moins puissant", "Dieu le plus puissant"],
  ["Couleur banale", "Couleur sexy"],
  ["Tu en bénéficie", "Tout le monde en bénéficie"],
  ["Mauvais president", "Bon president"],
  ["Inexpliqué", "Fou"],
  ["Dérivé", "Original"],
  ["Etiquette", "Bonnes manières"],
  ["Le pire", "Le meilleur"],
  ["Petit nombre", "Grand nombre"],
  ["Pas assez", "Trop"],
  ["Difficile à s'assoir dessus", "Facile à s'assoir dessus"],
  ["Compétence", "Talent"],
  ["Pire moment pour voyager dans le temps", "Meilleur moment pour voyager dans le temps"],
  ["câlinable", "non-câlinable"],
  ["Hétérogène", "Homogène"],
  ["Hors de contrôle", "Contrôlé"],
  ["Populaire", "Elitiste"],
  ["Non-partisan", "Partisan"],
  ["Nom de chien", "Nom de chat"],
  ["Fait peu connu", "Fait très connu"],
  ["Socialiste", "Capitaliste"],
  ["Mauvais bonbon", "Bon bonbon"],
  ["Traditionnel", "Radical"],
  ["Bon dans la bouche", "Mauvais dans la bouche"],
  ["Illégal", "Légal"],
  ["Jamais à l'heure", "Toujours à l'heure"],
  ["Ne vivra pas jusqu'à 100 ans", "Vivra jusqu'à 100 ans"],
  ["Méchant personnage de Disney", "Gentil personnage de Disney"],
  ["Similaire", "Identique"],
  ["Boîteux", "Ferme"],
  ["Sujet amusant", "Sujet serieux"],
  ["Sans parfum", "Parfumé"],
  ["Horizontal", "Vertical"],
  ["Petit", "Minuscule"],
  ["Monde de merde", "Monde merveilleux"],
  ["Mauvais conseil", "Bon conseil"],
  ["Illégal", "Prohibé"],
  ["Pas de l'art", "Art"],
  ["Rumeur", "Information"],
  ["Petit plaisir caché", "A ne juste pas faire"],
  ["Démodé", "Avant garde"],
  ["Vrai", "Faux"],
  ["Salutation normale", "Salutation bizarre"],
  ["Dictature", "Démocracie"],
  ["Impuissant", "Omnipotent"],
  ["Vape", "Ne vape pas"],
  ["Personne ennuyeuse", "Personne cool"],
  ["Livre qui mérite à être connu", "Livre sur-vendu"],
  ["Pensée profonde", "Pensée superficielle"],
  ["Mauvais modèle", "Bon modèle"],
  ["Sagesse populaire", "Superstition"],
  ["Pire corvée", "Meilleure corvée"],
  ["Espèce en voie de disparition", "Espèce en surpopulation"],
  ["Bleu", "Vert"],
  ["Fruit", "Légume"],
  ["Science", "Pseudoscience"],
  ["Banalité", "Sujet épineux"],
  ["Mauvais investissement", "Bon investissement"],
  ["Stationaire", "Mobile"],
  ["Problème local", "Problème global"],
  ["Excitant", "Terrifiant"],
  ["Intello", "Sportif"],
  ["Attendu", "Surprenant"],
  ["Personne que tu pourrais tabasser", "Personne qui pourrait te tabasser"],
  ["Limité", "Infini"],
  ["Evénement décontracté", "Evénement formel"],
  ["Phobie raisonnable", "Phobia irrationnelle"],
  ["Jeu peu connu", "Jeu sur-vendu"],
  ["Saint", "Sacrilège"],
  ["Doux", "Epicé"],
  ["Personne authentique", "Personne artificielle"],
  ["Contre-nature", "Naturel"],
  ["Secret", "Public"],
  ["Trop petit", "Trop grand"],
  ["Art", "Commerce"],
  ["Pokémon banal", "Pokémon sexy"],
  ["Sileucieux", "Bruyant"],
  ["Inclusif", "Exclusif"],
];

export const AllCards = [...SpectrumCards, ...AdvancedSpectrumCards];
